name: Primera automatizacion

on:
 push:
   branches:
     - main

jobs:
 prueba:
   runs-on: ubuntu-latest

   steps:
     - name: Simular proceso real
       run: |
         echo "Iniciando proceso..."
         echo "Comprobando codigo..."
         echo "Todo correcto ✅"
